/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["activate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetPassword_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generated-documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["archive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generated-documents/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["upload"];
        post?: never;
        delete: operations["remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organizationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_2"];
        trace?: never;
    };
    "/api/v1/organizations/{organizationId}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deactivate_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organizationId}/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDepartments"];
        put?: never;
        post: operations["createDepartment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organizationId}/departments/{departmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateDepartment"];
        trace?: never;
    };
    "/api/v1/organizations/{organizationId}/departments/{departmentId}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deactivateDepartment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organizationId}/letterhead": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["read"];
        put: operations["updateTexts"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organizationId}/letterhead/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["logo"];
        put: operations["uploadLogo"];
        post?: never;
        delete: operations["removeLogo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pca-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["currentPlan"];
        put?: never;
        post: operations["importPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["statistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_1"];
        trace?: never;
    };
    "/api/v1/procurement-processes/{id}/closure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes/{id}/demand-consolidation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["consolidation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes/{id}/dfds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dfds"];
        put?: never;
        post: operations["attachDfd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes/{id}/dfds/{dfdId}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dfdFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes/{id}/reopening": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reopen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes/{id}/trail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["trail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes/{processId}/documents/{documentType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["open"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes/{processId}/documents/{documentType}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finalizeDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes/{processId}/documents/{documentType}/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["history"];
        put?: never;
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes/{processId}/documents/{documentType}/generations/files/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes/{processId}/documents/{documentType}/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addSection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes/{processId}/documents/{documentType}/sections-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["reorderSections"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes/{processId}/documents/{documentType}/sections/{sectionCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["saveSection"];
        post?: never;
        delete: operations["removeSection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes/{processId}/documents/{documentType}/sections/{sectionCode}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generateSection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes/{processId}/documents/{documentType}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["versions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes/{processId}/documents/{documentType}/versions/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["comparison"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes/{processId}/pca": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["verify"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes/{processId}/pca/citation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/procurement-processes/{processId}/pca/declaration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["declare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update"];
        trace?: never;
    };
    "/api/v1/users/{userId}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["avatar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}/cpf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cpf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deactivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivateUserRequest: {
            cpf: string;
            /** Format: email */
            email: string;
            password: string;
        };
        AddSectionRequest: {
            anchorSectionCode: string;
            nested: boolean;
            title: string;
        };
        ArchiveSummaryResponse: {
            /** Format: int64 */
            finishedEtps: number;
            /** Format: int64 */
            lastSevenDays: number;
            /** Format: int64 */
            storageBytes: number;
            /** Format: int64 */
            thisMonth: number;
            /** Format: int64 */
            total: number;
        };
        ArchivedDocumentResponse: {
            /** @enum {string} */
            documentType: "COTACAO" | "ETP" | "MAPA" | "TR" | "EDITAL" | "CONTRATO";
            /** Format: int32 */
            documentVersion: number;
            files: components["schemas"]["GeneratedFileResponse"][];
            /** Format: date-time */
            generatedAt: string;
            /** Format: uuid */
            processId: string;
            processNumber: string;
            processObject: string;
        };
        AttachDfdRequest: {
            /** Format: uuid */
            departmentId: string;
            fileName: string;
            items: components["schemas"]["DemandItemRequest"][];
        };
        AuthenticationResponse: {
            accessToken: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: int64 */
            expiresIn: number;
            session: components["schemas"]["SessionResponse"];
            tokenType: string;
        };
        AvatarResponse: {
            /** Format: int32 */
            byteSize: number;
            mediaType: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BlockView: {
            dispensed: boolean;
            sectionCode: string;
            text: string;
            title: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        CloseProcurementProcessRequest: {
            justification?: string;
        };
        ConsolidatedItemView: {
            byDepartment: components["schemas"]["DepartmentDemandView"][];
            description: string;
            summable: boolean;
            total: number;
            unit: string;
        };
        CpfResponse: {
            cpf: string;
        };
        CreateDepartmentRequest: {
            acronym?: string;
            name: string;
        };
        CreateOrganizationRequest: {
            /** @enum {string} */
            entityType?: "PREFEITURA" | "CAMARA" | "AUTARQUIA" | "FUNDACAO" | "CONSORCIO" | "OUTRO";
            name: string;
            unit?: string;
        };
        CreateProcurementProcessRequest: {
            demandObject?: string;
            /** Format: uuid */
            departmentId: string;
            dfdFileName?: string;
            documents?: ("COTACAO" | "ETP" | "MAPA" | "TR" | "EDITAL" | "CONTRATO")[];
            estimatedValue: number;
            legalBasis?: string;
            /** @enum {string} */
            modality: "ELECTRONIC_AUCTION" | "COMPETITION" | "CONTEST" | "AUCTION" | "COMPETITIVE_DIALOGUE" | "DIRECT_AWARD_ARTICLE_75" | "SOLE_SOURCE" | "ACCREDITATION";
            objectDescription: string;
            urgency: boolean;
        };
        CreateUserRequest: {
            appointmentDecree?: string;
            cpf: string;
            /** Format: uuid */
            departmentId?: string;
            /** Format: email */
            email: string;
            jobTitle?: string;
            name: string;
            /** Format: uuid */
            organizationId?: string;
            /** @enum {string} */
            profileAccess: "ADMIN_GERAL" | "COORDENADOR" | "SERVIDOR";
            registrationNumber?: string;
        };
        DeactivationRequest: {
            reason: string;
        };
        DeclarePcaForesightRequest: {
            itemCode: string;
            note?: string;
        };
        DemandConsolidationResponse: {
            incongruences: components["schemas"]["IncongruenceView"][];
            items: components["schemas"]["ConsolidatedItemView"][];
        };
        DemandItemRequest: {
            /** Format: int32 */
            deliveryDays?: number;
            description: string;
            quantity: number;
            specification?: string;
            unit: string;
            unitPrice?: number;
        };
        DemandItemView: {
            /** Format: int32 */
            deliveryDays?: number;
            description: string;
            quantity: number;
            specification?: string;
            unit: string;
            unitPrice?: number;
        };
        DepartmentDemandView: {
            departmentName: string;
            quantity: number;
            unit: string;
        };
        DepartmentResponse: {
            acronym?: string;
            active: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            organizationId: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
        };
        DfdFileView: {
            /** Format: int32 */
            byteSize: number;
            mediaType: string;
            sha256: string;
        };
        DivergentValueView: {
            departmentName: string;
            value: string;
        };
        DocumentResponse: {
            body: components["schemas"]["BlockView"][];
            canGenerate: boolean;
            /** Format: int32 */
            currentVersion: number;
            /** @enum {string} */
            documentType: "COTACAO" | "ETP" | "MAPA" | "TR" | "EDITAL" | "CONTRATO";
            finalized: boolean;
            /** Format: uuid */
            id: string;
            pendingRequiredSections: string[];
            /** Format: uuid */
            processId: string;
            /** Format: int32 */
            progress: number;
            sections: components["schemas"]["SectionResponseView"][];
            silentGaps: string[];
        };
        DocumentVersionResponse: {
            body: components["schemas"]["BlockView"][];
            contentHash: string;
            /** Format: date-time */
            generatedAt: string;
            note: string;
            /** Format: int32 */
            version: number;
        };
        ErrataEntryView: {
            leiaSe?: string;
            ondeSeLe?: string;
            sectionCode: string;
            title: string;
        };
        FinalizeDocumentRequest: {
            rectificationDescribed?: boolean;
            rectificationDetail?: string;
            /** @enum {string} */
            rectificationKind?: "MATERIAL_ERROR" | "SUBSTANTIAL_CHANGE";
        };
        FindingResponse: {
            code?: string;
            demand: string;
            description?: string;
            estimatedValue?: number;
            foreseen: boolean;
            /** @enum {string} */
            kind?: "EXACT" | "TERMS" | "WIDENED" | "DECLARED";
            quantity?: number;
            unit?: string;
        };
        GenerateDocumentRequest: {
            formats: ("DOCX" | "PDF")[];
        };
        GeneratedFileResponse: {
            /** Format: int64 */
            byteSize: number;
            /** Format: int32 */
            documentVersion: number;
            fileName: string;
            /** @enum {string} */
            format: "DOCX" | "PDF";
            /** Format: date-time */
            generatedAt: string;
            /** Format: uuid */
            id: string;
            sha256: string;
            /** Format: int32 */
            templateVersion: number;
        };
        GeneratedSectionResponse: {
            text: string;
        };
        GenerationJobResponse: {
            /** Format: int32 */
            attempts: number;
            /** Format: int32 */
            documentVersion: number;
            error?: string;
            files: components["schemas"]["GeneratedFileResponse"][];
            /** Format: date-time */
            finishedAt?: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            requestedAt: string;
            succeeded: boolean;
        };
        ImportPcaPlanRequest: {
            content: string;
            fileName: string;
            /** Format: int32 */
            year: number;
        };
        IncongruenceView: {
            itemDescription: string;
            /** @enum {string} */
            kind: "UNIT" | "SPECIFICATION" | "UNIT_PRICE" | "DELIVERY_DEADLINE";
            values: components["schemas"]["DivergentValueView"][];
        };
        LetterheadResponse: {
            footerText: string;
            hasLogo: boolean;
            headerText: string;
            /** Format: int32 */
            version: number;
        };
        LoginRequest: {
            /**
             * @deprecated
             * @description Obsoleto desde 21/08/2026 (ADR-015): use identifier.
             */
            cpf?: string;
            identifier?: string;
            /** Format: uuid */
            organizationId?: string;
            password: string;
        };
        MembershipResponse: {
            active: boolean;
            /** Format: uuid */
            departmentId?: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
        };
        OrganizationResponse: {
            /** Format: date-time */
            createdAt: string;
            /** @enum {string} */
            entityType: "PREFEITURA" | "CAMARA" | "AUTARQUIA" | "FUNDACAO" | "CONSORCIO" | "OUTRO";
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            unit?: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
        };
        PageProcurementProcessResponse: {
            content?: components["schemas"]["ProcurementProcessResponse"][];
            empty?: boolean;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            number?: number;
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            size?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            paged?: boolean;
            sort?: components["schemas"]["SortObject"];
            unpaged?: boolean;
        };
        PasswordRecoveryRequest: {
            /** Format: email */
            email: string;
        };
        PasswordResetRequest: {
            password: string;
            token: string;
        };
        PcaPlanResponse: {
            /** Format: date-time */
            importedAt: string;
            /** Format: int32 */
            indexedItems: number;
            sourceFileName: string;
            /** Format: int32 */
            year: number;
        };
        PcaVerificationResponse: {
            citable: boolean;
            citation?: string;
            declaredNote?: string;
            findings: components["schemas"]["FindingResponse"][];
            foreseen: boolean;
            plan?: components["schemas"]["PcaPlanResponse"];
        };
        ProcessDfdResponse: {
            /** Format: uuid */
            departmentId: string;
            departmentName: string;
            file?: components["schemas"]["DfdFileView"];
            fileName: string;
            /** Format: uuid */
            id: string;
            items: components["schemas"]["DemandItemView"][];
            /** Format: date-time */
            submittedAt: string;
        };
        ProcessStatisticsResponse: {
            /** Format: int64 */
            active: number;
            /** Format: int64 */
            closed: number;
            /** Format: double */
            completionRate: number;
            /** Format: int64 */
            createdThisMonth: number;
            /** Format: int64 */
            pendingDocuments: number;
            /** Format: int64 */
            started: number;
        };
        ProcessTrailEntryResponse: {
            actorName?: string;
            event: string;
            /** Format: date-time */
            occurredAt: string;
            reason?: string;
        };
        ProcurementProcessResponse: {
            /** Format: date-time */
            closedAt?: string;
            closureNote?: string;
            /** Format: date-time */
            createdAt: string;
            demandObject?: string;
            /** Format: uuid */
            departmentId?: string;
            departmentName?: string;
            dfdFileName?: string;
            documents: ("COTACAO" | "ETP" | "MAPA" | "TR" | "EDITAL" | "CONTRATO")[];
            estimatedValue?: number;
            /** Format: uuid */
            id: string;
            legalBasis?: string;
            /** @enum {string} */
            modality: "ELECTRONIC_AUCTION" | "COMPETITION" | "CONTEST" | "AUCTION" | "COMPETITIVE_DIALOGUE" | "DIRECT_AWARD_ARTICLE_75" | "SOLE_SOURCE" | "ACCREDITATION";
            objectDescription: string;
            /** Format: uuid */
            organizationId: string;
            processNumber: string;
            /** Format: uuid */
            responsibleUserId?: string;
            responsibleUserName?: string;
            /** @enum {string} */
            status: "DRAFT" | "CLOSED";
            /** Format: date-time */
            updatedAt: string;
            urgency: boolean;
            /** Format: int64 */
            version: number;
        };
        ProvisionalPasswordResponse: {
            provisionalPassword: string;
        };
        ReopenProcurementProcessRequest: {
            reason: string;
        };
        ReorderSectionsRequest: {
            sectionCodesInOrder: string[];
        };
        SaveSectionRequest: {
            content?: string;
            dispensationJustification?: string;
        };
        SectionDiffView: {
            /** @enum {string} */
            change: "ADDED" | "REMOVED" | "CHANGED" | "UNCHANGED";
            currentText?: string;
            previousText?: string;
            sectionCode: string;
            title: string;
        };
        SectionResponseView: {
            content: string;
            dispensationJustification?: string;
            hint?: string;
            legalBasis?: string;
            /** @enum {string} */
            origin: "CATALOG" | "AD_HOC";
            /** Format: int32 */
            position: number;
            required: boolean;
            resolved: boolean;
            sectionCode: string;
            title: string;
        };
        SessionResponse: {
            activeMembership?: components["schemas"]["MembershipResponse"];
            organization?: components["schemas"]["OrganizationResponse"];
            permissions: ("PROFILE_READ" | "USER_READ" | "USER_MANAGE" | "ORGANIZATION_READ" | "ORGANIZATION_MANAGE" | "PLATFORM_ADMIN")[];
            user: components["schemas"]["SessionUserResponse"];
        };
        SessionUserResponse: {
            appointmentDecree?: string;
            cpf?: string;
            email: string;
            /** Format: uuid */
            id: string;
            jobTitle?: string;
            /** Format: date-time */
            lastAccessAt?: string;
            name: string;
            passwordChangeRequired: boolean;
            /** @enum {string} */
            profileAccess: "ADMIN_GERAL" | "COORDENADOR" | "SERVIDOR";
            registrationNumber?: string;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE" | "PENDING_ACTIVATION";
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        UpdateDepartmentRequest: {
            acronym?: string;
            name: string;
        };
        UpdateLetterheadRequest: {
            footerText?: string;
            headerText?: string;
        };
        UpdateOrganizationRequest: {
            /** @enum {string} */
            entityType?: "PREFEITURA" | "CAMARA" | "AUTARQUIA" | "FUNDACAO" | "CONSORCIO" | "OUTRO";
            name: string;
            unit?: string;
        };
        UpdateProcurementProcessRequest: {
            changeNote?: string;
            demandObject?: string;
            dfdFileName?: string;
            documents?: ("COTACAO" | "ETP" | "MAPA" | "TR" | "EDITAL" | "CONTRATO")[];
            estimatedValue: number;
            legalBasis?: string;
            /** @enum {string} */
            modality: "ELECTRONIC_AUCTION" | "COMPETITION" | "CONTEST" | "AUCTION" | "COMPETITIVE_DIALOGUE" | "DIRECT_AWARD_ARTICLE_75" | "SOLE_SOURCE" | "ACCREDITATION";
            objectDescription: string;
            urgency: boolean;
        };
        UpdateUserRequest: {
            appointmentDecree?: string;
            /** Format: uuid */
            departmentId?: string;
            /** Format: email */
            email: string;
            jobTitle?: string;
            name: string;
            /** Format: uuid */
            organizationId?: string;
            /** @enum {string} */
            profileAccess: "ADMIN_GERAL" | "COORDENADOR" | "SERVIDOR";
            registrationNumber?: string;
        };
        UserResponse: {
            appointmentDecree?: string;
            cpf?: string;
            /** Format: date-time */
            createdAt: string;
            email: string;
            /** Format: uuid */
            id: string;
            jobTitle?: string;
            /** Format: date-time */
            lastAccessAt?: string;
            memberships: components["schemas"]["MembershipResponse"][];
            name: string;
            passwordChangeRequired: boolean;
            /** @enum {string} */
            profileAccess: "ADMIN_GERAL" | "COORDENADOR" | "SERVIDOR";
            provisionalPassword?: string;
            registrationNumber?: string;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE" | "PENDING_ACTIVATION";
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
        };
        UserSummaryResponse: {
            cpf?: string;
            email: string;
            /** Format: uuid */
            id: string;
            jobTitle?: string;
            /** Format: date-time */
            lastAccessAt?: string;
            memberships: components["schemas"]["MembershipResponse"][];
            name: string;
            /** @enum {string} */
            profileAccess: "ADMIN_GERAL" | "COORDENADOR" | "SERVIDOR";
            registrationNumber?: string;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE" | "PENDING_ACTIVATION";
        };
        VersionComparisonResponse: {
            errata: components["schemas"]["ErrataEntryView"][];
            /** Format: int32 */
            from: number;
            sections: components["schemas"]["SectionDiffView"][];
            /** Format: int32 */
            to: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    activate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthenticationResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordRecoveryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resetPassword_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthenticationResponse"];
                };
            };
        };
    };
    archive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ArchivedDocumentResponse"][];
                };
            };
        };
    };
    summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ArchiveSummaryResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AvatarResponse"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizationResponse"][];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizationResponse"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizationResponse"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizationResponse"];
                };
            };
        };
    };
    deactivate_1: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeactivationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizationResponse"];
                };
            };
        };
    };
    listDepartments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DepartmentResponse"][];
                };
            };
        };
    };
    createDepartment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDepartmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DepartmentResponse"];
                };
            };
        };
    };
    updateDepartment: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                organizationId: string;
                departmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDepartmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DepartmentResponse"];
                };
            };
        };
    };
    deactivateDepartment: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                organizationId: string;
                departmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeactivationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DepartmentResponse"];
                };
            };
        };
    };
    read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LetterheadResponse"];
                };
            };
        };
    };
    updateTexts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLetterheadRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LetterheadResponse"];
                };
            };
        };
    };
    logo: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    uploadLogo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LetterheadResponse"];
                };
            };
        };
    };
    removeLogo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LetterheadResponse"];
                };
            };
        };
    };
    currentPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PcaPlanResponse"];
                };
            };
        };
    };
    importPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportPcaPlanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PcaPlanResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                status?: "DRAFT" | "CLOSED";
                search?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageProcurementProcessResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProcurementProcessRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProcurementProcessResponse"];
                };
            };
        };
    };
    statistics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProcessStatisticsResponse"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProcurementProcessResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProcurementProcessRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProcurementProcessResponse"];
                };
            };
        };
    };
    close: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseProcurementProcessRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProcurementProcessResponse"];
                };
            };
        };
    };
    consolidation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DemandConsolidationResponse"];
                };
            };
        };
    };
    dfds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProcessDfdResponse"][];
                };
            };
        };
    };
    attachDfd: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    dados: components["schemas"]["AttachDfdRequest"];
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProcessDfdResponse"];
                };
            };
        };
    };
    dfdFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                dfdId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    reopen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReopenProcurementProcessRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProcurementProcessResponse"];
                };
            };
        };
    };
    trail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProcessTrailEntryResponse"][];
                };
            };
        };
    };
    open: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                processId: string;
                documentType: "COTACAO" | "ETP" | "MAPA" | "TR" | "EDITAL" | "CONTRATO";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentResponse"];
                };
            };
        };
    };
    finalizeDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                processId: string;
                documentType: "COTACAO" | "ETP" | "MAPA" | "TR" | "EDITAL" | "CONTRATO";
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FinalizeDocumentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentResponse"];
                };
            };
        };
    };
    history: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                processId: string;
                documentType: "COTACAO" | "ETP" | "MAPA" | "TR" | "EDITAL" | "CONTRATO";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GenerationJobResponse"][];
                };
            };
        };
    };
    generate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                processId: string;
                documentType: "COTACAO" | "ETP" | "MAPA" | "TR" | "EDITAL" | "CONTRATO";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateDocumentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GenerationJobResponse"];
                };
            };
        };
    };
    download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                processId: string;
                documentType: "COTACAO" | "ETP" | "MAPA" | "TR" | "EDITAL" | "CONTRATO";
                fileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    addSection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                processId: string;
                documentType: "COTACAO" | "ETP" | "MAPA" | "TR" | "EDITAL" | "CONTRATO";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddSectionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentResponse"];
                };
            };
        };
    };
    reorderSections: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                processId: string;
                documentType: "COTACAO" | "ETP" | "MAPA" | "TR" | "EDITAL" | "CONTRATO";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderSectionsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentResponse"];
                };
            };
        };
    };
    saveSection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                processId: string;
                documentType: "COTACAO" | "ETP" | "MAPA" | "TR" | "EDITAL" | "CONTRATO";
                sectionCode: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveSectionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentResponse"];
                };
            };
        };
    };
    removeSection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                processId: string;
                documentType: "COTACAO" | "ETP" | "MAPA" | "TR" | "EDITAL" | "CONTRATO";
                sectionCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentResponse"];
                };
            };
        };
    };
    generateSection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                processId: string;
                documentType: "COTACAO" | "ETP" | "MAPA" | "TR" | "EDITAL" | "CONTRATO";
                sectionCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GeneratedSectionResponse"];
                };
            };
        };
    };
    versions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                processId: string;
                documentType: "COTACAO" | "ETP" | "MAPA" | "TR" | "EDITAL" | "CONTRATO";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentVersionResponse"][];
                };
            };
        };
    };
    comparison: {
        parameters: {
            query: {
                from: number;
                to: number;
            };
            header?: never;
            path: {
                processId: string;
                documentType: "COTACAO" | "ETP" | "MAPA" | "TR" | "EDITAL" | "CONTRATO";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VersionComparisonResponse"];
                };
            };
        };
    };
    verify: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                processId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PcaVerificationResponse"];
                };
            };
        };
    };
    cite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                processId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PcaVerificationResponse"];
                };
            };
        };
    };
    declare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                processId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeclarePcaForesightRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PcaVerificationResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                organizationId?: string;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserSummaryResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    avatar: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    cpf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CpfResponse"];
                };
            };
        };
    };
    deactivate: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeactivationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProvisionalPasswordResponse"];
                };
            };
        };
    };
}
